/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContractorAssignment = IDL.Record({
  'endDate' : IDL.Opt(IDL.Text),
  'allocationPercent' : IDL.Nat,
  'contractor' : IDL.Text,
  'project' : IDL.Text,
  'startDate' : IDL.Text,
});
export const Contractor = IDL.Record({
  'status' : IDL.Text,
  'country' : IDL.Text,
  'contractStart' : IDL.Text,
  'name' : IDL.Text,
  'agency' : IDL.Text,
  'contractEnd' : IDL.Text,
  'email' : IDL.Text,
  'hourlyRateUsd' : IDL.Nat,
  'department' : IDL.Text,
});
export const Contract = IDL.Record({
  'status' : IDL.Text,
  'title' : IDL.Text,
  'endDate' : IDL.Text,
  'kind' : IDL.Text,
  'vendor' : IDL.Text,
  'department' : IDL.Text,
  'valueUsd' : IDL.Nat,
  'startDate' : IDL.Text,
});
export const Customer = IDL.Record({
  'country' : IDL.Text,
  'signupDate' : IDL.Text,
  'plan' : IDL.Text,
  'accountManager' : IDL.Text,
  'monthlyRevenueUsd' : IDL.Nat,
  'companyName' : IDL.Text,
  'churnDate' : IDL.Opt(IDL.Text),
  'industry' : IDL.Text,
});
export const Department = IDL.Record({
  'foundedYear' : IDL.Nat,
  'name' : IDL.Text,
  'annualBudgetUsd' : IDL.Nat,
  'costCenter' : IDL.Text,
});
export const EmployeeAssignment = IDL.Record({
  'endDate' : IDL.Opt(IDL.Text),
  'allocationPercent' : IDL.Nat,
  'employee' : IDL.Text,
  'project' : IDL.Text,
  'startDate' : IDL.Text,
});
export const Employee = IDL.Record({
  'manager' : IDL.Opt(IDL.Text),
  'country' : IDL.Text,
  'hireDate' : IDL.Text,
  'name' : IDL.Text,
  'office' : IDL.Text,
  'email' : IDL.Text,
  'level' : IDL.Nat,
  'jobTitle' : IDL.Text,
  'terminationDate' : IDL.Opt(IDL.Text),
  'salaryUsd' : IDL.Nat,
  'department' : IDL.Text,
  'employmentStatus' : IDL.Text,
  'vacationDaysRemaining' : IDL.Nat,
});
export const Expense = IDL.Record({
  'date' : IDL.Text,
  'submittedBy' : IDL.Text,
  'approvalStatus' : IDL.Text,
  'category' : IDL.Text,
  'amountUsd' : IDL.Nat,
  'payee' : IDL.Text,
  'department' : IDL.Text,
  'project' : IDL.Opt(IDL.Text),
});
export const InternAssignment = IDL.Record({
  'allocationPercent' : IDL.Nat,
  'intern' : IDL.Text,
  'project' : IDL.Text,
});
export const Intern = IDL.Record({
  'mentor' : IDL.Text,
  'endDate' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'university' : IDL.Text,
  'department' : IDL.Text,
  'monthlyStipendUsd' : IDL.Nat,
  'startDate' : IDL.Text,
});
export const Invoice = IDL.Record({
  'issueDate' : IDL.Text,
  'status' : IDL.Text,
  'contract' : IDL.Opt(IDL.Text),
  'dueDate' : IDL.Text,
  'paidDate' : IDL.Opt(IDL.Text),
  'vendor' : IDL.Text,
  'amountUsd' : IDL.Nat,
});
export const Office = IDL.Record({
  'country' : IDL.Text,
  'openedDate' : IDL.Text,
  'city' : IDL.Text,
  'isHq' : IDL.Bool,
  'addressLine' : IDL.Text,
  'capacity' : IDL.Nat,
});
export const Product = IDL.Record({
  'name' : IDL.Text,
  'annualRevenueUsd' : IDL.Nat,
  'codename' : IDL.Text,
  'launchDate' : IDL.Text,
  'lifecycle' : IDL.Text,
  'department' : IDL.Text,
});
export const Project = IDL.Record({
  'plannedEndDate' : IDL.Text,
  'status' : IDL.Text,
  'actualEndDate' : IDL.Opt(IDL.Text),
  'lead' : IDL.Text,
  'name' : IDL.Text,
  'codename' : IDL.Text,
  'department' : IDL.Text,
  'budgetUsd' : IDL.Nat,
  'product' : IDL.Opt(IDL.Text),
  'startDate' : IDL.Text,
});
export const Vendor = IDL.Record({
  'paymentTermsDays' : IDL.Nat,
  'taxId' : IDL.Text,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'createdDate' : IDL.Text,
  'primaryContactName' : IDL.Text,
});

export const idlService = IDL.Service({
  '__contractorAssignments' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(ContractorAssignment)],
      ['query'],
    ),
  '__contractors' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Contractor)],
      ['query'],
    ),
  '__contracts' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Contract)],
      ['query'],
    ),
  '__customers' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Customer)],
      ['query'],
    ),
  '__departments' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Department)],
      ['query'],
    ),
  '__employeeAssignments' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(EmployeeAssignment)],
      ['query'],
    ),
  '__employees' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Employee)],
      ['query'],
    ),
  '__expenses' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  '__internAssignments' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(InternAssignment)],
      ['query'],
    ),
  '__interns' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Intern)],
      ['query'],
    ),
  '__invoices' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Invoice)],
      ['query'],
    ),
  '__offices' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Office)],
      ['query'],
    ),
  '__products' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Product)],
      ['query'],
    ),
  '__projects' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Project)],
      ['query'],
    ),
  '__vendors' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Vendor)],
      ['query'],
    ),
  'getAllContractorAssignments' : IDL.Func(
      [],
      [IDL.Vec(ContractorAssignment)],
      ['query'],
    ),
  'getAllContractors' : IDL.Func([], [IDL.Vec(Contractor)], ['query']),
  'getAllContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
  'getAllEmployeeAssignments' : IDL.Func(
      [],
      [IDL.Vec(EmployeeAssignment)],
      ['query'],
    ),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getAllInternAssignments' : IDL.Func(
      [],
      [IDL.Vec(InternAssignment)],
      ['query'],
    ),
  'getAllInterns' : IDL.Func([], [IDL.Vec(Intern)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllOffices' : IDL.Func([], [IDL.Vec(Office)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'uploadContractorAssignments' : IDL.Func(
      [IDL.Vec(ContractorAssignment)],
      [],
      [],
    ),
  'uploadContractors' : IDL.Func([IDL.Vec(Contractor)], [], []),
  'uploadContracts' : IDL.Func([IDL.Vec(Contract)], [], []),
  'uploadCustomers' : IDL.Func([IDL.Vec(Customer)], [], []),
  'uploadDepartments' : IDL.Func([IDL.Vec(Department)], [], []),
  'uploadEmployeeAssignments' : IDL.Func([IDL.Vec(EmployeeAssignment)], [], []),
  'uploadEmployees' : IDL.Func([IDL.Vec(Employee)], [], []),
  'uploadExpenses' : IDL.Func([IDL.Vec(Expense)], [], []),
  'uploadInternAssignments' : IDL.Func([IDL.Vec(InternAssignment)], [], []),
  'uploadInterns' : IDL.Func([IDL.Vec(Intern)], [], []),
  'uploadInvoices' : IDL.Func([IDL.Vec(Invoice)], [], []),
  'uploadOffices' : IDL.Func([IDL.Vec(Office)], [], []),
  'uploadProducts' : IDL.Func([IDL.Vec(Product)], [], []),
  'uploadProjects' : IDL.Func([IDL.Vec(Project)], [], []),
  'uploadVendors' : IDL.Func([IDL.Vec(Vendor)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContractorAssignment = IDL.Record({
    'endDate' : IDL.Opt(IDL.Text),
    'allocationPercent' : IDL.Nat,
    'contractor' : IDL.Text,
    'project' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const Contractor = IDL.Record({
    'status' : IDL.Text,
    'country' : IDL.Text,
    'contractStart' : IDL.Text,
    'name' : IDL.Text,
    'agency' : IDL.Text,
    'contractEnd' : IDL.Text,
    'email' : IDL.Text,
    'hourlyRateUsd' : IDL.Nat,
    'department' : IDL.Text,
  });
  const Contract = IDL.Record({
    'status' : IDL.Text,
    'title' : IDL.Text,
    'endDate' : IDL.Text,
    'kind' : IDL.Text,
    'vendor' : IDL.Text,
    'department' : IDL.Text,
    'valueUsd' : IDL.Nat,
    'startDate' : IDL.Text,
  });
  const Customer = IDL.Record({
    'country' : IDL.Text,
    'signupDate' : IDL.Text,
    'plan' : IDL.Text,
    'accountManager' : IDL.Text,
    'monthlyRevenueUsd' : IDL.Nat,
    'companyName' : IDL.Text,
    'churnDate' : IDL.Opt(IDL.Text),
    'industry' : IDL.Text,
  });
  const Department = IDL.Record({
    'foundedYear' : IDL.Nat,
    'name' : IDL.Text,
    'annualBudgetUsd' : IDL.Nat,
    'costCenter' : IDL.Text,
  });
  const EmployeeAssignment = IDL.Record({
    'endDate' : IDL.Opt(IDL.Text),
    'allocationPercent' : IDL.Nat,
    'employee' : IDL.Text,
    'project' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const Employee = IDL.Record({
    'manager' : IDL.Opt(IDL.Text),
    'country' : IDL.Text,
    'hireDate' : IDL.Text,
    'name' : IDL.Text,
    'office' : IDL.Text,
    'email' : IDL.Text,
    'level' : IDL.Nat,
    'jobTitle' : IDL.Text,
    'terminationDate' : IDL.Opt(IDL.Text),
    'salaryUsd' : IDL.Nat,
    'department' : IDL.Text,
    'employmentStatus' : IDL.Text,
    'vacationDaysRemaining' : IDL.Nat,
  });
  const Expense = IDL.Record({
    'date' : IDL.Text,
    'submittedBy' : IDL.Text,
    'approvalStatus' : IDL.Text,
    'category' : IDL.Text,
    'amountUsd' : IDL.Nat,
    'payee' : IDL.Text,
    'department' : IDL.Text,
    'project' : IDL.Opt(IDL.Text),
  });
  const InternAssignment = IDL.Record({
    'allocationPercent' : IDL.Nat,
    'intern' : IDL.Text,
    'project' : IDL.Text,
  });
  const Intern = IDL.Record({
    'mentor' : IDL.Text,
    'endDate' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'university' : IDL.Text,
    'department' : IDL.Text,
    'monthlyStipendUsd' : IDL.Nat,
    'startDate' : IDL.Text,
  });
  const Invoice = IDL.Record({
    'issueDate' : IDL.Text,
    'status' : IDL.Text,
    'contract' : IDL.Opt(IDL.Text),
    'dueDate' : IDL.Text,
    'paidDate' : IDL.Opt(IDL.Text),
    'vendor' : IDL.Text,
    'amountUsd' : IDL.Nat,
  });
  const Office = IDL.Record({
    'country' : IDL.Text,
    'openedDate' : IDL.Text,
    'city' : IDL.Text,
    'isHq' : IDL.Bool,
    'addressLine' : IDL.Text,
    'capacity' : IDL.Nat,
  });
  const Product = IDL.Record({
    'name' : IDL.Text,
    'annualRevenueUsd' : IDL.Nat,
    'codename' : IDL.Text,
    'launchDate' : IDL.Text,
    'lifecycle' : IDL.Text,
    'department' : IDL.Text,
  });
  const Project = IDL.Record({
    'plannedEndDate' : IDL.Text,
    'status' : IDL.Text,
    'actualEndDate' : IDL.Opt(IDL.Text),
    'lead' : IDL.Text,
    'name' : IDL.Text,
    'codename' : IDL.Text,
    'department' : IDL.Text,
    'budgetUsd' : IDL.Nat,
    'product' : IDL.Opt(IDL.Text),
    'startDate' : IDL.Text,
  });
  const Vendor = IDL.Record({
    'paymentTermsDays' : IDL.Nat,
    'taxId' : IDL.Text,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'createdDate' : IDL.Text,
    'primaryContactName' : IDL.Text,
  });
  
  return IDL.Service({
    '__contractorAssignments' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(ContractorAssignment)],
        ['query'],
      ),
    '__contractors' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Contractor)],
        ['query'],
      ),
    '__contracts' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Contract)],
        ['query'],
      ),
    '__customers' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Customer)],
        ['query'],
      ),
    '__departments' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Department)],
        ['query'],
      ),
    '__employeeAssignments' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(EmployeeAssignment)],
        ['query'],
      ),
    '__employees' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Employee)],
        ['query'],
      ),
    '__expenses' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    '__internAssignments' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(InternAssignment)],
        ['query'],
      ),
    '__interns' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Intern)],
        ['query'],
      ),
    '__invoices' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Invoice)],
        ['query'],
      ),
    '__offices' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Office)],
        ['query'],
      ),
    '__products' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    '__projects' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Project)],
        ['query'],
      ),
    '__vendors' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Vendor)],
        ['query'],
      ),
    'getAllContractorAssignments' : IDL.Func(
        [],
        [IDL.Vec(ContractorAssignment)],
        ['query'],
      ),
    'getAllContractors' : IDL.Func([], [IDL.Vec(Contractor)], ['query']),
    'getAllContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
    'getAllEmployeeAssignments' : IDL.Func(
        [],
        [IDL.Vec(EmployeeAssignment)],
        ['query'],
      ),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getAllInternAssignments' : IDL.Func(
        [],
        [IDL.Vec(InternAssignment)],
        ['query'],
      ),
    'getAllInterns' : IDL.Func([], [IDL.Vec(Intern)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllOffices' : IDL.Func([], [IDL.Vec(Office)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'uploadContractorAssignments' : IDL.Func(
        [IDL.Vec(ContractorAssignment)],
        [],
        [],
      ),
    'uploadContractors' : IDL.Func([IDL.Vec(Contractor)], [], []),
    'uploadContracts' : IDL.Func([IDL.Vec(Contract)], [], []),
    'uploadCustomers' : IDL.Func([IDL.Vec(Customer)], [], []),
    'uploadDepartments' : IDL.Func([IDL.Vec(Department)], [], []),
    'uploadEmployeeAssignments' : IDL.Func(
        [IDL.Vec(EmployeeAssignment)],
        [],
        [],
      ),
    'uploadEmployees' : IDL.Func([IDL.Vec(Employee)], [], []),
    'uploadExpenses' : IDL.Func([IDL.Vec(Expense)], [], []),
    'uploadInternAssignments' : IDL.Func([IDL.Vec(InternAssignment)], [], []),
    'uploadInterns' : IDL.Func([IDL.Vec(Intern)], [], []),
    'uploadInvoices' : IDL.Func([IDL.Vec(Invoice)], [], []),
    'uploadOffices' : IDL.Func([IDL.Vec(Office)], [], []),
    'uploadProducts' : IDL.Func([IDL.Vec(Product)], [], []),
    'uploadProjects' : IDL.Func([IDL.Vec(Project)], [], []),
    'uploadVendors' : IDL.Func([IDL.Vec(Vendor)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };