/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contract {
  'status' : string,
  'title' : string,
  'endDate' : string,
  'kind' : string,
  'vendor' : string,
  'department' : string,
  'valueUsd' : bigint,
  'startDate' : string,
}
export interface Contractor {
  'status' : string,
  'country' : string,
  'contractStart' : string,
  'name' : string,
  'agency' : string,
  'contractEnd' : string,
  'email' : string,
  'hourlyRateUsd' : bigint,
  'department' : string,
}
export interface ContractorAssignment {
  'endDate' : [] | [string],
  'allocationPercent' : bigint,
  'contractor' : string,
  'project' : string,
  'startDate' : string,
}
export interface Customer {
  'country' : string,
  'signupDate' : string,
  'plan' : string,
  'accountManager' : string,
  'monthlyRevenueUsd' : bigint,
  'companyName' : string,
  'churnDate' : [] | [string],
  'industry' : string,
}
export interface Department {
  'foundedYear' : bigint,
  'name' : string,
  'annualBudgetUsd' : bigint,
  'costCenter' : string,
}
export interface Employee {
  'manager' : [] | [string],
  'country' : string,
  'hireDate' : string,
  'name' : string,
  'office' : string,
  'email' : string,
  'level' : bigint,
  'jobTitle' : string,
  'terminationDate' : [] | [string],
  'salaryUsd' : bigint,
  'department' : string,
  'employmentStatus' : string,
  'vacationDaysRemaining' : bigint,
}
export interface EmployeeAssignment {
  'endDate' : [] | [string],
  'allocationPercent' : bigint,
  'employee' : string,
  'project' : string,
  'startDate' : string,
}
export interface Expense {
  'date' : string,
  'submittedBy' : string,
  'approvalStatus' : string,
  'category' : string,
  'amountUsd' : bigint,
  'payee' : string,
  'department' : string,
  'project' : [] | [string],
}
export interface Intern {
  'mentor' : string,
  'endDate' : string,
  'name' : string,
  'email' : string,
  'university' : string,
  'department' : string,
  'monthlyStipendUsd' : bigint,
  'startDate' : string,
}
export interface InternAssignment {
  'allocationPercent' : bigint,
  'intern' : string,
  'project' : string,
}
export interface Invoice {
  'issueDate' : string,
  'status' : string,
  'contract' : [] | [string],
  'dueDate' : string,
  'paidDate' : [] | [string],
  'vendor' : string,
  'amountUsd' : bigint,
}
export interface Office {
  'country' : string,
  'openedDate' : string,
  'city' : string,
  'isHq' : boolean,
  'addressLine' : string,
  'capacity' : bigint,
}
export interface Product {
  'name' : string,
  'annualRevenueUsd' : bigint,
  'codename' : string,
  'launchDate' : string,
  'lifecycle' : string,
  'department' : string,
}
export interface Project {
  'plannedEndDate' : string,
  'status' : string,
  'actualEndDate' : [] | [string],
  'lead' : string,
  'name' : string,
  'codename' : string,
  'department' : string,
  'budgetUsd' : bigint,
  'product' : [] | [string],
  'startDate' : string,
}
export interface Vendor {
  'paymentTermsDays' : bigint,
  'taxId' : string,
  'country' : string,
  'name' : string,
  'createdDate' : string,
  'primaryContactName' : string,
}
export interface _SERVICE {
  '__contractorAssignments' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<ContractorAssignment>
  >,
  '__contractors' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<Contractor>
  >,
  '__contracts' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Contract>>,
  '__customers' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Customer>>,
  '__departments' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<Department>
  >,
  '__employeeAssignments' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<EmployeeAssignment>
  >,
  '__employees' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Employee>>,
  '__expenses' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Expense>>,
  '__internAssignments' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<InternAssignment>
  >,
  '__interns' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Intern>>,
  '__invoices' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Invoice>>,
  '__offices' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Office>>,
  '__products' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Product>>,
  '__projects' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Project>>,
  '__vendors' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Vendor>>,
  'getAllContractorAssignments' : ActorMethod<[], Array<ContractorAssignment>>,
  'getAllContractors' : ActorMethod<[], Array<Contractor>>,
  'getAllContracts' : ActorMethod<[], Array<Contract>>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllDepartments' : ActorMethod<[], Array<Department>>,
  'getAllEmployeeAssignments' : ActorMethod<[], Array<EmployeeAssignment>>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllExpenses' : ActorMethod<[], Array<Expense>>,
  'getAllInternAssignments' : ActorMethod<[], Array<InternAssignment>>,
  'getAllInterns' : ActorMethod<[], Array<Intern>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllOffices' : ActorMethod<[], Array<Office>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllVendors' : ActorMethod<[], Array<Vendor>>,
  'uploadContractorAssignments' : ActorMethod<
    [Array<ContractorAssignment>],
    undefined
  >,
  'uploadContractors' : ActorMethod<[Array<Contractor>], undefined>,
  'uploadContracts' : ActorMethod<[Array<Contract>], undefined>,
  'uploadCustomers' : ActorMethod<[Array<Customer>], undefined>,
  'uploadDepartments' : ActorMethod<[Array<Department>], undefined>,
  'uploadEmployeeAssignments' : ActorMethod<
    [Array<EmployeeAssignment>],
    undefined
  >,
  'uploadEmployees' : ActorMethod<[Array<Employee>], undefined>,
  'uploadExpenses' : ActorMethod<[Array<Expense>], undefined>,
  'uploadInternAssignments' : ActorMethod<[Array<InternAssignment>], undefined>,
  'uploadInterns' : ActorMethod<[Array<Intern>], undefined>,
  'uploadInvoices' : ActorMethod<[Array<Invoice>], undefined>,
  'uploadOffices' : ActorMethod<[Array<Office>], undefined>,
  'uploadProducts' : ActorMethod<[Array<Product>], undefined>,
  'uploadProjects' : ActorMethod<[Array<Project>], undefined>,
  'uploadVendors' : ActorMethod<[Array<Vendor>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];