/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    name: string;
    annualRevenueUsd: bigint;
    codename: string;
    launchDate: string;
    lifecycle: string;
    department: string;
}
export interface EmployeeAssignment {
    endDate?: string;
    allocationPercent: bigint;
    employee: string;
    project: string;
    startDate: string;
}
export interface Invoice {
    issueDate: string;
    status: string;
    contract?: string;
    dueDate: string;
    paidDate?: string;
    vendor: string;
    amountUsd: bigint;
}
export interface Expense {
    date: string;
    submittedBy: string;
    approvalStatus: string;
    category: string;
    amountUsd: bigint;
    payee: string;
    department: string;
    project?: string;
}
export interface Customer {
    country: string;
    signupDate: string;
    plan: string;
    accountManager: string;
    monthlyRevenueUsd: bigint;
    companyName: string;
    churnDate?: string;
    industry: string;
}
export interface Office {
    country: string;
    openedDate: string;
    city: string;
    isHq: boolean;
    addressLine: string;
    capacity: bigint;
}
export interface Department {
    foundedYear: bigint;
    name: string;
    annualBudgetUsd: bigint;
    costCenter: string;
}
export interface ContractorAssignment {
    endDate?: string;
    allocationPercent: bigint;
    contractor: string;
    project: string;
    startDate: string;
}
export interface Contractor {
    status: string;
    country: string;
    contractStart: string;
    name: string;
    agency: string;
    contractEnd: string;
    email: string;
    hourlyRateUsd: bigint;
    department: string;
}
export interface Employee {
    manager?: string;
    country: string;
    hireDate: string;
    name: string;
    office: string;
    email: string;
    level: bigint;
    jobTitle: string;
    terminationDate?: string;
    salaryUsd: bigint;
    department: string;
    employmentStatus: string;
    vacationDaysRemaining: bigint;
}
export interface Contract {
    status: string;
    title: string;
    endDate: string;
    kind: string;
    vendor: string;
    department: string;
    valueUsd: bigint;
    startDate: string;
}
export interface InternAssignment {
    allocationPercent: bigint;
    intern: string;
    project: string;
}
export interface Intern {
    mentor: string;
    endDate: string;
    name: string;
    email: string;
    university: string;
    department: string;
    monthlyStipendUsd: bigint;
    startDate: string;
}
export interface Vendor {
    paymentTermsDays: bigint;
    taxId: string;
    country: string;
    name: string;
    createdDate: string;
    primaryContactName: string;
}
export interface Project {
    plannedEndDate: string;
    status: string;
    actualEndDate?: string;
    lead: string;
    name: string;
    codename: string;
    department: string;
    budgetUsd: bigint;
    product?: string;
    startDate: string;
}
export interface backendInterface {
    __contractorAssignments(io: bigint | null, count: bigint | null): Promise<Array<ContractorAssignment>>;
    __contractors(io: bigint | null, count: bigint | null): Promise<Array<Contractor>>;
    __contracts(io: bigint | null, count: bigint | null): Promise<Array<Contract>>;
    __customers(io: bigint | null, count: bigint | null): Promise<Array<Customer>>;
    __departments(io: bigint | null, count: bigint | null): Promise<Array<Department>>;
    __employeeAssignments(io: bigint | null, count: bigint | null): Promise<Array<EmployeeAssignment>>;
    __employees(io: bigint | null, count: bigint | null): Promise<Array<Employee>>;
    __expenses(io: bigint | null, count: bigint | null): Promise<Array<Expense>>;
    __internAssignments(io: bigint | null, count: bigint | null): Promise<Array<InternAssignment>>;
    __interns(io: bigint | null, count: bigint | null): Promise<Array<Intern>>;
    __invoices(io: bigint | null, count: bigint | null): Promise<Array<Invoice>>;
    __offices(io: bigint | null, count: bigint | null): Promise<Array<Office>>;
    __products(io: bigint | null, count: bigint | null): Promise<Array<Product>>;
    __projects(io: bigint | null, count: bigint | null): Promise<Array<Project>>;
    __vendors(io: bigint | null, count: bigint | null): Promise<Array<Vendor>>;
    getAllContractorAssignments(): Promise<Array<ContractorAssignment>>;
    getAllContractors(): Promise<Array<Contractor>>;
    getAllContracts(): Promise<Array<Contract>>;
    getAllCustomers(): Promise<Array<Customer>>;
    getAllDepartments(): Promise<Array<Department>>;
    getAllEmployeeAssignments(): Promise<Array<EmployeeAssignment>>;
    getAllEmployees(): Promise<Array<Employee>>;
    getAllExpenses(): Promise<Array<Expense>>;
    getAllInternAssignments(): Promise<Array<InternAssignment>>;
    getAllInterns(): Promise<Array<Intern>>;
    getAllInvoices(): Promise<Array<Invoice>>;
    getAllOffices(): Promise<Array<Office>>;
    getAllProducts(): Promise<Array<Product>>;
    getAllProjects(): Promise<Array<Project>>;
    getAllVendors(): Promise<Array<Vendor>>;
    uploadContractorAssignments(data: Array<ContractorAssignment>): Promise<void>;
    uploadContractors(data: Array<Contractor>): Promise<void>;
    uploadContracts(data: Array<Contract>): Promise<void>;
    uploadCustomers(data: Array<Customer>): Promise<void>;
    uploadDepartments(data: Array<Department>): Promise<void>;
    uploadEmployeeAssignments(data: Array<EmployeeAssignment>): Promise<void>;
    uploadEmployees(data: Array<Employee>): Promise<void>;
    uploadExpenses(data: Array<Expense>): Promise<void>;
    uploadInternAssignments(data: Array<InternAssignment>): Promise<void>;
    uploadInterns(data: Array<Intern>): Promise<void>;
    uploadInvoices(data: Array<Invoice>): Promise<void>;
    uploadOffices(data: Array<Office>): Promise<void>;
    uploadProducts(data: Array<Product>): Promise<void>;
    uploadProjects(data: Array<Project>): Promise<void>;
    uploadVendors(data: Array<Vendor>): Promise<void>;
}
import type { ContractorAssignment as _ContractorAssignment, Customer as _Customer, Employee as _Employee, EmployeeAssignment as _EmployeeAssignment, Expense as _Expense, Invoice as _Invoice, Project as _Project } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __contractorAssignments(arg0: bigint | null, arg1: bigint | null): Promise<Array<ContractorAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.__contractorAssignments(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__contractorAssignments(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async __contractors(arg0: bigint | null, arg1: bigint | null): Promise<Array<Contractor>> {
        if (this.processError) {
            try {
                const result = await this.actor.__contractors(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__contractors(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __contracts(arg0: bigint | null, arg1: bigint | null): Promise<Array<Contract>> {
        if (this.processError) {
            try {
                const result = await this.actor.__contracts(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__contracts(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __customers(arg0: bigint | null, arg1: bigint | null): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.__customers(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__customers(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async __departments(arg0: bigint | null, arg1: bigint | null): Promise<Array<Department>> {
        if (this.processError) {
            try {
                const result = await this.actor.__departments(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__departments(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __employeeAssignments(arg0: bigint | null, arg1: bigint | null): Promise<Array<EmployeeAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.__employeeAssignments(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__employeeAssignments(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async __employees(arg0: bigint | null, arg1: bigint | null): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.__employees(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__employees(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async __expenses(arg0: bigint | null, arg1: bigint | null): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.__expenses(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__expenses(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async __internAssignments(arg0: bigint | null, arg1: bigint | null): Promise<Array<InternAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.__internAssignments(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__internAssignments(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __interns(arg0: bigint | null, arg1: bigint | null): Promise<Array<Intern>> {
        if (this.processError) {
            try {
                const result = await this.actor.__interns(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__interns(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __invoices(arg0: bigint | null, arg1: bigint | null): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.__invoices(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__invoices(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async __offices(arg0: bigint | null, arg1: bigint | null): Promise<Array<Office>> {
        if (this.processError) {
            try {
                const result = await this.actor.__offices(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__offices(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __products(arg0: bigint | null, arg1: bigint | null): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.__products(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__products(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __projects(arg0: bigint | null, arg1: bigint | null): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.__projects(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__projects(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async __vendors(arg0: bigint | null, arg1: bigint | null): Promise<Array<Vendor>> {
        if (this.processError) {
            try {
                const result = await this.actor.__vendors(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__vendors(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllContractorAssignments(): Promise<Array<ContractorAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContractorAssignments();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContractorAssignments();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContractors(): Promise<Array<Contractor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContractors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContractors();
            return result;
        }
    }
    async getAllContracts(): Promise<Array<Contract>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContracts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContracts();
            return result;
        }
    }
    async getAllCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDepartments(): Promise<Array<Department>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDepartments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDepartments();
            return result;
        }
    }
    async getAllEmployeeAssignments(): Promise<Array<EmployeeAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployeeAssignments();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployeeAssignments();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployees();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployees();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExpenses();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExpenses();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInternAssignments(): Promise<Array<InternAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInternAssignments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInternAssignments();
            return result;
        }
    }
    async getAllInterns(): Promise<Array<Intern>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInterns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInterns();
            return result;
        }
    }
    async getAllInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvoices();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvoices();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOffices(): Promise<Array<Office>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOffices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOffices();
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return result;
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVendors(): Promise<Array<Vendor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVendors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVendors();
            return result;
        }
    }
    async uploadContractorAssignments(arg0: Array<ContractorAssignment>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadContractorAssignments(to_candid_vec_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadContractorAssignments(to_candid_vec_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadContractors(arg0: Array<Contractor>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadContractors(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadContractors(arg0);
            return result;
        }
    }
    async uploadContracts(arg0: Array<Contract>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadContracts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadContracts(arg0);
            return result;
        }
    }
    async uploadCustomers(arg0: Array<Customer>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadCustomers(to_candid_vec_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadCustomers(to_candid_vec_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadDepartments(arg0: Array<Department>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDepartments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDepartments(arg0);
            return result;
        }
    }
    async uploadEmployeeAssignments(arg0: Array<EmployeeAssignment>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadEmployeeAssignments(to_candid_vec_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadEmployeeAssignments(to_candid_vec_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadEmployees(arg0: Array<Employee>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadEmployees(to_candid_vec_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadEmployees(to_candid_vec_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadExpenses(arg0: Array<Expense>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadExpenses(to_candid_vec_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadExpenses(to_candid_vec_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadInternAssignments(arg0: Array<InternAssignment>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadInternAssignments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadInternAssignments(arg0);
            return result;
        }
    }
    async uploadInterns(arg0: Array<Intern>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadInterns(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadInterns(arg0);
            return result;
        }
    }
    async uploadInvoices(arg0: Array<Invoice>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadInvoices(to_candid_vec_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadInvoices(to_candid_vec_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadOffices(arg0: Array<Office>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadOffices(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadOffices(arg0);
            return result;
        }
    }
    async uploadProducts(arg0: Array<Product>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadProducts(arg0);
            return result;
        }
    }
    async uploadProjects(arg0: Array<Project>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadProjects(to_candid_vec_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadProjects(to_candid_vec_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadVendors(arg0: Array<Vendor>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadVendors(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadVendors(arg0);
            return result;
        }
    }
}
function from_candid_ContractorAssignment_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContractorAssignment): ContractorAssignment {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Customer_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Customer): Customer {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_EmployeeAssignment_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeAssignment): EmployeeAssignment {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Employee_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Employee): Employee {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Expense_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expense): Expense {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate: [] | [string];
    allocationPercent: bigint;
    employee: string;
    project: string;
    startDate: string;
}): {
    endDate?: string;
    allocationPercent: bigint;
    employee: string;
    project: string;
    startDate: string;
} {
    return {
        endDate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.endDate)),
        allocationPercent: value.allocationPercent,
        employee: value.employee,
        project: value.project,
        startDate: value.startDate
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manager: [] | [string];
    country: string;
    hireDate: string;
    name: string;
    office: string;
    email: string;
    level: bigint;
    jobTitle: string;
    terminationDate: [] | [string];
    salaryUsd: bigint;
    department: string;
    employmentStatus: string;
    vacationDaysRemaining: bigint;
}): {
    manager?: string;
    country: string;
    hireDate: string;
    name: string;
    office: string;
    email: string;
    level: bigint;
    jobTitle: string;
    terminationDate?: string;
    salaryUsd: bigint;
    department: string;
    employmentStatus: string;
    vacationDaysRemaining: bigint;
} {
    return {
        manager: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.manager)),
        country: value.country,
        hireDate: value.hireDate,
        name: value.name,
        office: value.office,
        email: value.email,
        level: value.level,
        jobTitle: value.jobTitle,
        terminationDate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.terminationDate)),
        salaryUsd: value.salaryUsd,
        department: value.department,
        employmentStatus: value.employmentStatus,
        vacationDaysRemaining: value.vacationDaysRemaining
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    submittedBy: string;
    approvalStatus: string;
    category: string;
    amountUsd: bigint;
    payee: string;
    department: string;
    project: [] | [string];
}): {
    date: string;
    submittedBy: string;
    approvalStatus: string;
    category: string;
    amountUsd: bigint;
    payee: string;
    department: string;
    project?: string;
} {
    return {
        date: value.date,
        submittedBy: value.submittedBy,
        approvalStatus: value.approvalStatus,
        category: value.category,
        amountUsd: value.amountUsd,
        payee: value.payee,
        department: value.department,
        project: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.project))
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    issueDate: string;
    status: string;
    contract: [] | [string];
    dueDate: string;
    paidDate: [] | [string];
    vendor: string;
    amountUsd: bigint;
}): {
    issueDate: string;
    status: string;
    contract?: string;
    dueDate: string;
    paidDate?: string;
    vendor: string;
    amountUsd: bigint;
} {
    return {
        issueDate: value.issueDate,
        status: value.status,
        contract: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.contract)),
        dueDate: value.dueDate,
        paidDate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.paidDate)),
        vendor: value.vendor,
        amountUsd: value.amountUsd
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    plannedEndDate: string;
    status: string;
    actualEndDate: [] | [string];
    lead: string;
    name: string;
    codename: string;
    department: string;
    budgetUsd: bigint;
    product: [] | [string];
    startDate: string;
}): {
    plannedEndDate: string;
    status: string;
    actualEndDate?: string;
    lead: string;
    name: string;
    codename: string;
    department: string;
    budgetUsd: bigint;
    product?: string;
    startDate: string;
} {
    return {
        plannedEndDate: value.plannedEndDate,
        status: value.status,
        actualEndDate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.actualEndDate)),
        lead: value.lead,
        name: value.name,
        codename: value.codename,
        department: value.department,
        budgetUsd: value.budgetUsd,
        product: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.product)),
        startDate: value.startDate
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate: [] | [string];
    allocationPercent: bigint;
    contractor: string;
    project: string;
    startDate: string;
}): {
    endDate?: string;
    allocationPercent: bigint;
    contractor: string;
    project: string;
    startDate: string;
} {
    return {
        endDate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.endDate)),
        allocationPercent: value.allocationPercent,
        contractor: value.contractor,
        project: value.project,
        startDate: value.startDate
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: string;
    signupDate: string;
    plan: string;
    accountManager: string;
    monthlyRevenueUsd: bigint;
    companyName: string;
    churnDate: [] | [string];
    industry: string;
}): {
    country: string;
    signupDate: string;
    plan: string;
    accountManager: string;
    monthlyRevenueUsd: bigint;
    companyName: string;
    churnDate?: string;
    industry: string;
} {
    return {
        country: value.country,
        signupDate: value.signupDate,
        plan: value.plan,
        accountManager: value.accountManager,
        monthlyRevenueUsd: value.monthlyRevenueUsd,
        companyName: value.companyName,
        churnDate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.churnDate)),
        industry: value.industry
    };
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Employee>): Array<Employee> {
    return value.map((x)=>from_candid_Employee_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expense>): Array<Expense> {
    return value.map((x)=>from_candid_Expense_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContractorAssignment>): Array<ContractorAssignment> {
    return value.map((x)=>from_candid_ContractorAssignment_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Customer>): Array<Customer> {
    return value.map((x)=>from_candid_Customer_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmployeeAssignment>): Array<EmployeeAssignment> {
    return value.map((x)=>from_candid_EmployeeAssignment_n10(_uploadFile, _downloadFile, x));
}
function to_candid_ContractorAssignment_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContractorAssignment): _ContractorAssignment {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_Customer_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Customer): _Customer {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_EmployeeAssignment_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeAssignment): _EmployeeAssignment {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_Employee_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Employee): _Employee {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_Expense_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Expense): _Expense {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_Invoice_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Invoice): _Invoice {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_Project_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Project): _Project {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate?: string;
    allocationPercent: bigint;
    contractor: string;
    project: string;
    startDate: string;
}): {
    endDate: [] | [string];
    allocationPercent: bigint;
    contractor: string;
    project: string;
    startDate: string;
} {
    return {
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        allocationPercent: value.allocationPercent,
        contractor: value.contractor,
        project: value.project,
        startDate: value.startDate
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: string;
    signupDate: string;
    plan: string;
    accountManager: string;
    monthlyRevenueUsd: bigint;
    companyName: string;
    churnDate?: string;
    industry: string;
}): {
    country: string;
    signupDate: string;
    plan: string;
    accountManager: string;
    monthlyRevenueUsd: bigint;
    companyName: string;
    churnDate: [] | [string];
    industry: string;
} {
    return {
        country: value.country,
        signupDate: value.signupDate,
        plan: value.plan,
        accountManager: value.accountManager,
        monthlyRevenueUsd: value.monthlyRevenueUsd,
        companyName: value.companyName,
        churnDate: value.churnDate ? candid_some(value.churnDate) : candid_none(),
        industry: value.industry
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate?: string;
    allocationPercent: bigint;
    employee: string;
    project: string;
    startDate: string;
}): {
    endDate: [] | [string];
    allocationPercent: bigint;
    employee: string;
    project: string;
    startDate: string;
} {
    return {
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        allocationPercent: value.allocationPercent,
        employee: value.employee,
        project: value.project,
        startDate: value.startDate
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manager?: string;
    country: string;
    hireDate: string;
    name: string;
    office: string;
    email: string;
    level: bigint;
    jobTitle: string;
    terminationDate?: string;
    salaryUsd: bigint;
    department: string;
    employmentStatus: string;
    vacationDaysRemaining: bigint;
}): {
    manager: [] | [string];
    country: string;
    hireDate: string;
    name: string;
    office: string;
    email: string;
    level: bigint;
    jobTitle: string;
    terminationDate: [] | [string];
    salaryUsd: bigint;
    department: string;
    employmentStatus: string;
    vacationDaysRemaining: bigint;
} {
    return {
        manager: value.manager ? candid_some(value.manager) : candid_none(),
        country: value.country,
        hireDate: value.hireDate,
        name: value.name,
        office: value.office,
        email: value.email,
        level: value.level,
        jobTitle: value.jobTitle,
        terminationDate: value.terminationDate ? candid_some(value.terminationDate) : candid_none(),
        salaryUsd: value.salaryUsd,
        department: value.department,
        employmentStatus: value.employmentStatus,
        vacationDaysRemaining: value.vacationDaysRemaining
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    submittedBy: string;
    approvalStatus: string;
    category: string;
    amountUsd: bigint;
    payee: string;
    department: string;
    project?: string;
}): {
    date: string;
    submittedBy: string;
    approvalStatus: string;
    category: string;
    amountUsd: bigint;
    payee: string;
    department: string;
    project: [] | [string];
} {
    return {
        date: value.date,
        submittedBy: value.submittedBy,
        approvalStatus: value.approvalStatus,
        category: value.category,
        amountUsd: value.amountUsd,
        payee: value.payee,
        department: value.department,
        project: value.project ? candid_some(value.project) : candid_none()
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    issueDate: string;
    status: string;
    contract?: string;
    dueDate: string;
    paidDate?: string;
    vendor: string;
    amountUsd: bigint;
}): {
    issueDate: string;
    status: string;
    contract: [] | [string];
    dueDate: string;
    paidDate: [] | [string];
    vendor: string;
    amountUsd: bigint;
} {
    return {
        issueDate: value.issueDate,
        status: value.status,
        contract: value.contract ? candid_some(value.contract) : candid_none(),
        dueDate: value.dueDate,
        paidDate: value.paidDate ? candid_some(value.paidDate) : candid_none(),
        vendor: value.vendor,
        amountUsd: value.amountUsd
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    plannedEndDate: string;
    status: string;
    actualEndDate?: string;
    lead: string;
    name: string;
    codename: string;
    department: string;
    budgetUsd: bigint;
    product?: string;
    startDate: string;
}): {
    plannedEndDate: string;
    status: string;
    actualEndDate: [] | [string];
    lead: string;
    name: string;
    codename: string;
    department: string;
    budgetUsd: bigint;
    product: [] | [string];
    startDate: string;
} {
    return {
        plannedEndDate: value.plannedEndDate,
        status: value.status,
        actualEndDate: value.actualEndDate ? candid_some(value.actualEndDate) : candid_none(),
        lead: value.lead,
        name: value.name,
        codename: value.codename,
        department: value.department,
        budgetUsd: value.budgetUsd,
        product: value.product ? candid_some(value.product) : candid_none(),
        startDate: value.startDate
    };
}
function to_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ContractorAssignment>): Array<_ContractorAssignment> {
    return value.map((x)=>to_candid_ContractorAssignment_n25(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Customer>): Array<_Customer> {
    return value.map((x)=>to_candid_Customer_n28(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<EmployeeAssignment>): Array<_EmployeeAssignment> {
    return value.map((x)=>to_candid_EmployeeAssignment_n31(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Employee>): Array<_Employee> {
    return value.map((x)=>to_candid_Employee_n34(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Expense>): Array<_Expense> {
    return value.map((x)=>to_candid_Expense_n37(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Invoice>): Array<_Invoice> {
    return value.map((x)=>to_candid_Invoice_n40(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Project>): Array<_Project> {
    return value.map((x)=>to_candid_Project_n43(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
